### ISSUE TITLE
VCLcompilationfailed

### ISSUE THREAD

**Issue by RAFFENNEvalentin** [IBM/varnish-operator#102]
Hi again,

is it possible to launch some additional library for vcl. In my case, this is the specific one : https://github.com/varnish/libvmod-digest

I built a docker image before but it does not work with all the ecosystem you've created.

Thanks a lot

**Comment by cin** [comment]
AFAIK, this should work; but I don't think we've ever tested this scenario. I think you should be able to include the library in your docker image and reference it in your VCL like you would any other library. Can you provide some more details about what you tried? I can try to reproduce the issue.

**Comment by RAFFENNEvalentin** [comment]
Ok i manage the issue quiet differently. I plug my installation on your varnish container and it works perfectly.
Do you want my dockerfile for the documentation ? My way seems to be specific but in fact it is the most general way to install any vcl module. But i admit that it is not the simplest way

**Comment by cin** [comment]
Post what you had to do. Maybe it makes sense to add a section to the docs to help others with the same issue?
