### ISSUE TITLE
Varnish Cluster using  sharding director ?

### ISSUE THREAD

**Issue by arthurzinck** [IBM/varnish-operator#104]
Hi Craig, we are pretty satisfied about how `VarnishCluster` works but, as we have 3 `VarnishCluster` replicas for resiliency we need 3 requests to build up cache on the 3 instances. 

I was wondering if there is a way to use sharding as [they would do it here in this example](https://info.varnish-software.com/blog/creating-self-routing-varnish-cluster).
And avoid going back to the app, if one of the Varnish instances may have it in cache. But automatically set up by the `controller` inside the `backends.vcl.tmpl`

Thanks,
Arthur

**Comment by cin** [comment]
There sure is. :) You can change the behavior by altering the VCL to suit your needs, but here are the docs we have around the feature. https://github.com/IBM/varnish-operator/blob/54c5aff649c8c13652d232a19d8451d8ac37ee1e/docs/vcl-configuration.md#advanced-vcl-with-varnish-sharding. Let me know if you have any problems getting it setup.

**Comment by arthurzinck** [comment]
This is awesome, thank you for your answer. 
I seemed to have issue with the `acl_cluster` in the example you provided me. This configuration was sending a `503 Backend fetch failed` until I modified the example a bit and add the `/32` inside the brackets.
I have done a PR to fix this, maybe you will agree to merge it : https://github.com/IBM/varnish-operator/pull/105

**Comment by cin** [comment]
@arthurzinck I merged this change into my fork. For now (and maybe going forward), my fork is only going to be maintained.

**Comment by arthurzinck** [comment]
Hello Craig, yes for sure. I will be using your fork from now one :+1: 
If you need help maintaining I can give a hand from time to time
