### ISSUE TITLE
Varnish operator grafana dashboard pulls in too many metrics

### ISSUE THREAD

**Issue by kscharm** [IBM/varnish-operator#24]
The Grafana dashboard that is deployed with the operator pulls in metrics from other pods in the cluster that are unrelated to varnish. See the `CPU usage` and `Memory usage` graphs in the dashboard. We should narrow the scope of the metrics that are used in the dashboard. Additionally, the `CPU usage` graph appears to use time when it should be using percentage.

**Comment by kscharm** [comment]
@tomashibm let me know if you have anything else to add here ^

**Comment by tomashibm** [comment]
I'd also set a filter by the namespace. Wouldn't hurt and if we decide to support deploying multiple operators in a cluster (but in different namespaces), this part will be ready for that feature.
