### ISSUE TITLE
Reference varnish-operator in https://operatorhub.io/

### ISSUE THREAD

**Issue by arthurlogilab** [IBM/varnish-operator#3]
Looking for an operator for varnish, I headed to https://operatorhub.io/ but couldn't find any.

Luckily I also did a search and found this project (and will soon test it out). 

Any reason why this operator is not referenced on https://operatorhub.io/ ?

**Comment by tomashibm** [comment]
Hey, sorry for radiosilence. 
Yeah, we definitely want to do it, just haven't had the time for that yet. We plan to do it in the nearest future, but can't give exact timelines.

**Comment by cin** [comment]
We're actually getting close to releasing the operator on operator hub. We just awaiting approval for the name and logo. Hopefully that will happen soon. We'll follow up here when it's released. Thanks!

**Comment by tomashibm** [comment]
resolved by #31 
Listed both in operatorhub.com and in Openshift's web console interface.
