### ISSUE TITLE
Upgrade PodDisruptionBudget version

### ISSUE THREAD

**Issue by tomashibm** [IBM/varnish-operator#46]
Getting warnings in the logs:
W0921 11:26:08.102693       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget

**Comment by cin** [comment]
So we have time but will need to support the v1beta version for a period unfortunately. What k8s version was v1 of PDB introduced?

**Comment by tomashibm** [comment]
In 1.21. So we actually have to upgrade when we're closer to 1.25. Otherwise we'd have to drop 1.21 <= support
