### ISSUE TITLE
Standard installation doesn't work

### ISSUE THREAD

**Issue by tebaly** [IBM/varnish-operator#49]
https://ibm.github.io/varnish-operator/installation.html

Hello. Doesn't work on a managed cluster (as service [scaleway] ). Probably because there is no master server

W1022 04:58:46.584001 1 client_config.go:608] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.
{"level":"info","msg":"patching webhook configurations 'varnish-operator-webhook-configuration' mutating=true, validating=true, failurePolicy=Fail","source":"k8s/k8s.go:39","time":"2021-10-22T04:58:46Z"}
{"err":"the server could not find the requested resource","level":"fatal","msg":"failed getting validating webhook","source":"k8s/k8s.go:48","time":"2021-10-22T04:58:46Z"}

**Comment by tomashibm** [comment]
@tebaly The fix is released. It was an issue with one of our dependencies that didn't support Kubernetes 1.22. Should work fine now.
