### ISSUE TITLE
Storage Backends for Varnish

### ISSUE THREAD

**Issue by hsawhney09** [IBM/varnish-operator#56]
Wondering if the current implementation supports using file as the storage backend for Varnish and if the file can be configured to use a PV/host mount ?

**Comment by cin** [comment]
We do not currently support file backed storage for Varnish. Maybe my logic here is wrong, but I think you should use a different tool if you need persistence. Varnish is a cache, and we didn't have any use cases for persistence at the time. What is your use case? Maybe there's an angle we're not thinking about it from.

**Comment by hsawhney09** [comment]
Our use case revolves around serving multi GB files that can some amount to multi TB. We are looking to use the file backend https://varnish-cache.org/docs/trunk/users-guide/storage-backends.html#file

**Comment by cin** [comment]
Sorry for the delay. We'll discuss this next week and see if this is something that we can support. @tomashibm @antonioua  FYI. @hsawhney09 we also will accept PRs if this is something you have the expertise and time required to implement.
