### ISSUE TITLE
Frontend Requests on grafana dashboard shows wrong number.

### ISSUE THREAD

**Issue by blbird** [IBM/varnish-operator#57]
If there is over 10 varnish. if the varnish-*-1 is selected on grafana dashboard, it shows sum of pods' request which start with varnish-*-1. For example, if there are varnishes which names are from varnish-1 to varnish-10 and varnish-1 is selected, frontend requests shows sum varnish-1's requests and varnish-10's requests.

**Comment by cin** [comment]
Thanks for submitting this issue. We'll take a look into it. We also accept PRs if you're comfortable with contributing. :)

**Comment by blbird** [comment]
@cin No problem :-). Actually I tried to fix that, but some similar issues seem to be there. So, I think that it is not easy to me.

**Comment by cin** [comment]
No worries. @tomashibm is going to take a look into this next week.

**Comment by tomashibm** [comment]
@blbird fixed in the latest release

**Comment by blbird** [comment]
@tomashibm Thank you.
