### ISSUE TITLE
Migrate from helm v2 to helm v3

### ISSUE THREAD

**Issue by arthurlogilab** [IBM/varnish-operator#6]
Trying out `make e2e-test` I get 

```
[snip]
Error: unknown command "init" for "helm"

Did you mean this?
	lint

Run 'helm --help' for usage.
```

Had helmv3 installed, switching to helmv2 seems to get rid of this error.

**Comment by arthurlogilab** [comment]
After resetting my .helm configuration I get : 

```
+ helm init --service-account=tiller --upgrade --wait
Creating /home/arthur/.helm/repository/repositories.yaml 
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com 
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
make: *** [Makefile:148: e2e-tests] Error 1
```

Did I miss something ?

**Comment by cin** [comment]
I'm not sure what's up with the `helm init` failing, but obviously we missed running our e2e tests with helm3. We validated that the charts work with helm3 a while back; but since helm v3.5.2 came out, we should run through another round of validation. We're debating dropping support for helm2 while we're making these changes but haven't come to a consensus as of yet.

**Comment by allen-servedio** [comment]
You are probably running into https://github.com/helm/helm/releases/tag/v3.4.0 or https://github.com/helm/helm/releases/tag/v2.17.0 (depending on the version of helm). 

You have to set the `stable` repo to `https://charts.helm.sh/stable` as the googleapis one is deprecated. They did a bit of a hard cut over in Helm (failing builds if you still had the old one defined).

**Comment by arthurlogilab** [comment]
Upgrading to helm v2.17.0 seems to fix the problem. Thanks for taking the time to look at this. 

I'll leave the issue open for the discussion about helmv3
