### ISSUE TITLE
Add value to specify nodePort

### ISSUE THREAD

**Issue by uqix** [IBM/varnish-operator#71]

**Comment by cin** [comment]
I'm not sure exactly what you're asking. We support using a `nodePort` service type to front the varnish pods if that's to what you're referring. You can set the `service.type` as described [here](https://ibm.github.io/varnish-operator/varnish-cluster-configuration.html). You can specify the port as well.

**Comment by uqix** [comment]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/10142314/183550417-7ee0dae7-e302-43f1-8f3a-409f0ba2378a.png">


Sorry for not being clear, I mean after setting `service.type` to `NodePort` we need to specify the port like 30000 instead of randomly(32124) allocated by k8s.

**Comment by cin** [comment]
Is the `service.port` config not working? We may have a bug. @tomashibm maybe you will be able to get to this before I will. If not, np I'll take a look when I can. Thanks!

**Comment by uqix** [comment]
My config:

```yaml
  service:
    type: NodePort
    port: 80
    # nodePort: 30000
```

I think `service.port` is bound to clusterIP, maybe a separate option is needed?

**Comment by tomashibm** [comment]
See what you mean @uqix . @cin not a bug, just a config we need to expose. I guess @uqix you're hitting your k8s nodes directly from outside and that's why you need control over which port you open there for Varnish, right?

Besides nodeport for Varnish do you also need the same for the metrics port?

**Comment by uqix** [comment]
@tomashibm exactly as you said, 

* first we allocate nodePorts manually to avoid conflicts, so better support specifying nodePort for all three ports(varnish/controller/metric)
* second we use nodePort for external cloud LB

thanks

**Comment by tomashibm** [comment]
@uqix which k8s version you're running on? we want to include a change that drops support for k8s 1.20<=. If you're using and older we'll do separate releases for these two changes

**Comment by uqix** [comment]
We use v1.24, thanks

**Comment by tomashibm** [comment]
released in the latest version @uqix
