### ISSUE TITLE
Default entrypointVCLFileContent issues

### ISSUE THREAD

**Issue by NITEMAN** [IBM/varnish-operator#78]
[Varnish by default appends its `builtin.vcl` to custom logic](https://varnish-cache.org/docs/trunk/users-guide/vcl-built-in-code.html#built-in-vcl)

Right now, default `entrypointVCLFileContent` contains several calls to return preventing `builtin.vcl` execution this could cause several issues or weird behaviors.

IMHO, `entrypointVCLFileContent` should better stick to what is needed and improve [its documentation](https://ibm.github.io/varnish-operator/vcl-configuration.html)

Issues/weirdness encountered with current `entrypointVCLFileContent`:
* **All** request are transformed to `GET`: Varnish by default only deals with `GET` & `HEAD`, see https://github.com/varnishcache/varnish-cache/blob/6.5/bin/varnishd/builtin.vcl#L65, but currently `entrypointVCLFileContent` includes an insensitive `return (hash);` preventing built-in logic to kick in. AFAIK it's not documented
* Only url is used for request hashing: This makes the config unsafe when backends varying responses upon `host` header. Imaging a PHP application listening to both `api.my.app/node/1` and `www.my.app/node/1`. AFAIK it's not documented
* [Stale objects are never used](https://github.com/IBM/varnish-operator/blob/main/pkg/varnishcluster/controller/varnishcluster_default_vcl.go#L95): AFAIK it's not documented

I'll suggest to remove unneeded returns from `entrypointVCLFileContent`, it may both limit weirdness and ease maintanibility

Best regards

**Comment by cin** [comment]
Hey @NITEMAN, thanks for the issue and PR. There are a few things I need to check up on with our devops folks before proceeding. I think the returns on some of the functions are to explicitly not run the built-in VCL. The `vcl_init` and `vcl_fini` are essentially NOOPs, right (bc all the built-in functions simply return)? In regard to the hashing and `vcl_recv` changes, I think this change would break a lot of our existing use cases. I will double check on that. Additionally, I think the logic there is the bare minimum required for most use cases and letting that extra logic run would only slow varnish down. We are dealing with systems that are taking in tens of thousands of requests per second, so every call needs to be as responsive as possible.

I think you've pointed out some places on which we should at least update the documentation to avoid confusion. I'll get back with you in regard to the other topics discussed above.

**Comment by NITEMAN** [comment]
Hello @cin  , thanks for the blazing fast feedback!

I'm pretty sure your devops folks will find out the changes to be almost neutral (unless you are relying upon the transparent method change). I didn't touch any return that could avoid builtin collisions ;)

Talking about pure performance, I'll admit we've only seen an order of magnitude less (sustained ~800req/s)... but in my experience ~20 lines of VCL logic will be hardly noticeable (over bare metal / virtualized, this will be our very first containerized setup) and should be very easy to benchmark.

Anyway a mere doc update will be great for newcomers like me! Please tell me if I can help anyhow
