### ISSUE TITLE
Build for arm

### ISSUE THREAD

**Issue by tszyszko** [IBM/varnish-operator#81]
Would be useful to support arm64

**Comment by cin** [comment]
@tszyszko, thanks for the issue. Sorry for the delay. The actual golang binaries are built with amd64 as the `GOARCH`. If you can, please elaborate on what you're trying to do.

**Comment by allen-servedio** [comment]
@cin AWS's Graviton processors (as well as MacBook M1) are ARM based processors. I suspect people want to run the binaries on those machines.

**Comment by cin** [comment]
@tszyszko please try out the 0.34.0 release and let us know how it goes. Thanks for the suggestion and making me learn about multi-platform builds. :) The only issues I have had are with [podman on an M1 mac](https://github.com/IBM/varnish-operator/pull/83#issuecomment-1287376800), but I'll be curious to see if others have any issues.

**Comment by tszyszko** [comment]
See #89
