### ISSUE TITLE
Could I separate registry/repository:tag override for VarnishClusters Object ?

### ISSUE THREAD

**Issue by arthurzinck** [IBM/varnish-operator#90]
Hey,
I would like to override only the the Registry the same way I did with the `Varnish-Operator`(https://github.com/IBM/varnish-operator/pull/87), because I don't want to pull my images from internet each time I don't have it on the node.

I would be open to do the PR

Thanks,
Arthur

**Comment by arthurzinck** [comment]
I could do the same as VictoriaMetrics did : https://github.com/VictoriaMetrics/operator/blob/633f5fcef44a901085d48b9de079af79be52739d/config/crd/bases/operator.victoriametrics.com_vmagents.yaml#L705

**Comment by cin** [comment]
This is a good point. We should probably stick with the same scheme so as to maintain backward compatibility. While we're at it, does it make sense to do this for the other images too?

**Comment by arthurzinck** [comment]
Yes, I think it does, as I would like to override with my own ECR for all images used by Varnish Cluster and Operator in my Kubernetes cluster

**Comment by arthurzinck** [comment]
So in fact, after a closer look in pair with @chubchubsancho, there is no need to do that.
If you overide the image of the Operator, it will set a environment variable. This CONTAINER_IMAGE is then used to set image for the VarnishCluster if you don't specify them. 
You can find the code that does just that in https://github.com/IBM/varnish-operator/blob/f004366cc6f0b5f04b46f8739ca9195fc8f8e107/pkg/varnishcluster/config/config.go#L55
