### ISSUE TITLE
Could we add an event to the worklfow docs

### ISSUE THREAD

**Issue by arthurzinck** [IBM/varnish-operator#91]
Hey, 

Could we add an event for push on `main` branch to the workflow that generates the Documentation ?

Thanks,
Arthur

**Comment by arthurzinck** [comment]
This would solve my issue : https://github.com/IBM/varnish-operator/pull/92

**Comment by cin** [comment]
Right now, the docs are only updated on release.  This ensures the docs are in sync with the latest release. However, I see your point in that we have some docs that are currently out of date. I'm actually not sure what the best practices are for this topic. I'm really just waiting on the prometheus exporter PR to be merged before tagging a new release. I just knew both PRs were in the works but didn't want to create a tag for each. I'll do some poking around and see how others handle this situation.

**Comment by arthurzinck** [comment]
Okay I understand, maybe we could just leave it as it is then

**Comment by cin** [comment]
Resolved by #92
