### ISSUE TITLE
Add Priority Class to VarnishClusters Pod

### ISSUE THREAD

**Issue by arthurzinck** [IBM/varnish-operator#97]
Hey,
I would like to add the possibility to set priority Class. As for now there is no possibility of setting them, it take the default priority class and get evicted just like a normal pod. This is an issue as it is not a normal pod, those pods hold in their RAM all the cache.

Thanks,
Arthur

**Comment by cin** [comment]
Well, I just learned something new. :) It sounds like a good idea. From what I just read it sounds like `ResourceQuota`s should be set as well when defining an object as a priority class. Are there any other issues or "gotchas" that we should consider?

**Comment by arthurzinck** [comment]
Hello Craig, `ResourceQuotas` seems like a whole other notion than `PriorityClass`. We use priorityClass because our cluster shrink and scale all the time and we need the scheduler to know which pod is "okay" to lose and which pod is a no no.

Please find the [PR](https://github.com/BedrockStreaming/tech.bedrockstreaming.com/pull/397) we did with @chubchubsancho 

Thanks,
Arthur

**Comment by cin** [comment]
Resolved by #98. Note that I have not tested this yet but will make some time to test this afternoon.
